### ISSUE TITLE
Just a little typo in documentation

### ISSUE THREAD

**Issue by ivan-dalmet** [Hyperting/hypertheme-editor#9]
Hi, I'm not sure if this is the right repo but I just found a little typo on the documentation "Get your lincese" -> "Get your license" 😉 

![image](https://user-images.githubusercontent.com/9749061/134523193-4b55d06e-9c6d-4987-9734-9f340ce7f6f5.png)

https://www.hyperthe.me/documentation/getting-started/pro

**Comment by it-nalon** [comment]
Hi, thank you very much for opening this issue! 💖

We've 

For now this is the right way to open documentation issues, we're preparing the Issue guidelines.
